theme: jekyll-theme-cayman
title: ["DeepArtic's Blog. Technology, coding and emulation"]
description: ["This is just a bunch of crazy ideas about technology, coding, virtualization and emulation that I need to share"]
